apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: cloud-specialization-project-frontend
  name: cloud-specialization-project-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloud-specialization-project-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.31.0 (a04ecdb9e)
      creationTimestamp: null
      labels:
        io.kompose.network/cloud-specialization-project-mynetwork: "true"
        io.kompose.service: cloud-specialization-project-frontend
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: cloud-specialization-project-frontend
          image: 441429649349.dkr.ecr.us-east-1.amazonaws.com/cloud_specialization_project_frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
